// Generated by CoffeeScript 1.7.1
(function() {
  this.FixtureHelper = (function() {
    function FixtureHelper() {}

    FixtureHelper.clear = function() {
      var fixtureJQuery;
      fixtureJQuery = $("#fixture");
      return fixtureJQuery.html("");
    };

    FixtureHelper.appendHTML = function(newHTML, times) {
      var fixtureJQuery, _i;
      if (times == null) {
        times = 1;
      }
      fixtureJQuery = $("#fixture");
      for (_i = 1; 1 <= times ? _i <= times : _i >= times; 1 <= times ? _i++ : _i--) {
        fixtureJQuery.append(newHTML);
      }
      return fixtureJQuery.get(0);
    };

    return FixtureHelper;

  })();

}).call(this);

//# sourceMappingURL=FixtureHelper.map
