// Generated by CoffeeScript 1.7.1
(function() {
  this.FixtureBuilder = (function() {
    function FixtureBuilder() {}

    FixtureBuilder.clear = function() {
      var fixtureJQuery;
      fixtureJQuery = $("#fixture");
      return fixtureJQuery.html("");
    };

    FixtureBuilder.appendHTML = function(newHTML, times) {
      var fixtureJQuery, _i;
      if (times == null) {
        times = 1;
      }
      fixtureJQuery = $("#fixture");
      for (_i = 1; 1 <= times ? _i <= times : _i >= times; 1 <= times ? _i++ : _i--) {
        fixtureJQuery.append(newHTML);
      }
      return fixtureJQuery.get(0);
    };

    return FixtureBuilder;

  })();

}).call(this);

//# sourceMappingURL=FixtureBuilder.map
