// Generated by CoffeeScript 1.7.1
(function() {
  describe("Interval", function() {
    beforeEach(function(done) {
      return done();
    });
    afterEach(function() {});
    it("must count any interval greater than 1 ms", function(done) {
      var interval;
      interval = new Interval();
      interval.start();
      return setTimeout(function() {
        interval.stop();
        expect(interval.timeInMs).toBeGreaterThan(1);
        return done();
      }, 2);
    });
    it("must count 0 if I check without start() or stop()", function() {
      var interval;
      interval = new Interval();
      return expect(interval.timeInMs).toBe(0);
    });
    return it("must count -1 if I check with start() but without stop()", function() {
      var interval;
      interval = new Interval();
      interval.start();
      return expect(interval.timeInMs).toBe(-1);
    });
  });

}).call(this);

//# sourceMappingURL=IntervalSpec.map
