// Generated by CoffeeScript 1.7.1
(function() {
  this.Interval = (function() {
    function Interval() {
      this.timeInMs = 0;
    }

    Interval.prototype.start = function() {
      this.timeInMs = -1;
      return this._startDate = new Date();
    };

    Interval.prototype.stop = function() {
      var endDate;
      endDate = new Date();
      return this.timeInMs = endDate - this._startDate;
    };

    Interval.prototype.test = function() {};

    return Interval;

  })();

}).call(this);

//# sourceMappingURL=Interval.map
