// Generated by CoffeeScript 1.9.3
(function() {
  describe("TemplateFactory", function() {
    var TemplateFactory;
    TemplateFactory = ObliqueNS.TemplateFactory;
    beforeEach(function() {
      return FixtureHelper.clear();
    });
    afterEach(function() {
      return FixtureHelper.clear();
    });
    it("must create a template from string", function() {
      var template, templateFactory;
      templateFactory = new TemplateFactory();
      template = templateFactory.createFromString("Hello {{this}}!");
      return expect(template.renderHTML("world")).toBe("Hello world!");
    });
    it("must create a template from tag", function() {
      var template, templateContent, templateFactory;
      templateContent = "<script id='hello' type='text/x-handlebars-template'>Hello {{this}}!</script>";
      FixtureHelper.appendHTML(templateContent);
      templateFactory = new TemplateFactory();
      template = templateFactory.createFromDOMElement($("#hello"));
      return expect(template.renderHTML("world")).toBe("Hello world!");
    });
    it("must create a template from Url", function() {
      var html, model, template, templateFactory;
      model = {
        title: "titulo",
        body: "cuerpo"
      };
      html = "<h1>titulo</h1><div>cuerpo</div>";
      templateFactory = new TemplateFactory();
      template = templateFactory.createFromUrl("/oblique-js/spec/templates/test_ok.hbs");
      return expect(template.renderHTML(model)).toBe(html);
    });
    return it("must throw an error if template is not found", function() {
      return expect(function() {
        return new TemplateFactory().createFromUrl("/patata.hbs");
      }).toThrow(new ObliqueNS.Error("template '/patata.hbs' not found"));
    });
  });

}).call(this);
