// Generated by CoffeeScript 1.7.1
(function() {
  this.ClockDirective = (function() {
    function ClockDirective(DOMElement) {
      var clockElement;
      clockElement = $(DOMElement);
      setInterval((function(_this) {
        return function() {
          var currentTime, hours, minutes, seconds;
          currentTime = new Date();
          hours = _this.pad(currentTime.getHours());
          minutes = _this.pad(currentTime.getMinutes());
          seconds = _this.pad(currentTime.getSeconds());
          return clockElement.html("Current time:" + hours + ":" + minutes + ":" + seconds);
        };
      })(this), 500);
    }

    ClockDirective.prototype.pad = function(number, digits) {
      if (digits == null) {
        digits = 2;
      }
      number = number.toString();
      while (number.length < digits) {
        number = "0" + number;
      }
      return number;
    };

    ClockDirective.CSS_EXPRESSION = "clock";

    return ClockDirective;

  })();

  Oblique().registerDirective(ClockDirective);

}).call(this);
