// Generated by CoffeeScript 1.10.0
(function() {
  var ParamParser;

  this.ObliqueNS = this.ObliqueNS || {};

  ParamParser = (function() {
    function ParamParser(params, separator) {
      var ch, currentParam, i, isInsideValue, len;
      if (separator == null) {
        separator = "&";
      }
      params = params.replace("#", "") + separator;
      this.hashParams = [];
      currentParam = "";
      isInsideValue = false;
      for (i = 0, len = params.length; i < len; i++) {
        ch = params[i];
        if (ch === ']' || ch === ')') {
          isInsideValue = false;
        }
        if (ch === '[' || ch === '(') {
          isInsideValue = true;
        }
        if (ch === separator && !isInsideValue) {
          this.hashParams.push(currentParam);
          currentParam = "";
          continue;
        }
        currentParam = currentParam + ch;
      }
    }

    return ParamParser;

  })();

  ObliqueNS.ParamParser = ParamParser;

}).call(this);
