// Generated by CoffeeScript 1.10.0
(function() {
  var Param, ParamParser;

  this.ObliqueNS = this.ObliqueNS || {};

  ParamParser = ObliqueNS.ParamParser;

  Param = (function() {
    function Param(name1) {
      this.name = name1;
      if (!this._isString(this.name)) {
        throw new ObliqueNS.Error("Param constructor must be called with first param string");
      }
    }

    Param.prototype._isString = function(value) {
      if (typeof value === 'string') {
        return true;
      }
      return false;
    };

    Param.containsChar = function(fullStr, char) {
      if (fullStr.indexOf(char) === -1) {
        return false;
      }
      return true;
    };

    Param.isEnclosedInChars = function(fullStr, charStart, charEnd) {
      if (fullStr[0] === charStart) {
        return true;
      }
      if (fullStr[fullStr.length - 1] === charEnd) {
        return true;
      }
      return false;
    };

    Param.stringIsNullOrEmpty = function(value) {
      if (value === void 0) {
        return true;
      }
      if (value.trim().length === 0) {
        return true;
      }
      return false;
    };

    Param.parse = function(strHashParam) {
      var hashArray, name, value;
      hashArray = new ParamParser(strHashParam, "=").hashParams;
      name = hashArray[0].trim();
      value = "";
      if (hashArray.length > 1) {
        value = hashArray[1].trim();
      }
      return {
        name: name,
        value: value
      };
    };

    Param.prototype.getLocationHash = function() {
      return "";
    };

    Param.prototype.isEmpty = function() {
      return true;
    };

    Param.prototype.valueIsEqualTo = function() {
      return true;
    };

    Param.prototype.containsValue = function() {
      return true;
    };

    Param.prototype.isInRange = function() {
      return true;
    };

    return Param;

  })();

  ObliqueNS.Param = Param;

}).call(this);
