// Generated by CoffeeScript 1.8.0
(function() {
  var Param;

  this.ObliqueNS = this.ObliqueNS || {};

  Param = (function() {
    function Param(name) {
      this.name = name;
      if (!this._isString(this.name)) {
        throw new ObliqueNS.Error("Param constructor must be called with first param string");
      }
    }

    Param.prototype._isString = function(value) {
      if (typeof value === 'string') {
        return true;
      }
      return false;
    };

    Param.containsChar = function(fullStr, char) {
      if (fullStr.indexOf(char) === -1) {
        return false;
      }
      return true;
    };

    Param.stringIsNullOrEmpty = function(value) {
      if (value === void 0) {
        return true;
      }
      if (value.trim().length === 0) {
        return true;
      }
      return false;
    };

    Param.parse = function(strHashParam) {
      var hashArray, name, value;
      hashArray = strHashParam.split("=");
      name = hashArray[0].trim();
      value = hashArray[1].trim();
      return {
        name: name,
        value: value
      };
    };

    Param.prototype.getLocationHash = function() {
      return "";
    };

    Param.prototype.isEmpty = function() {
      return true;
    };

    Param.prototype.valueIsEqualTo = function() {
      return true;
    };

    Param.prototype.containsValue = function() {
      return true;
    };

    Param.prototype.isInRange = function() {
      return true;
    };

    return Param;

  })();

  ObliqueNS.Param = Param;

}).call(this);
