// Generated by CoffeeScript 1.9.3
(function() {
  var EmptyParam,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.ObliqueNS = this.ObliqueNS || {};

  EmptyParam = (function(superClass) {
    extend(EmptyParam, superClass);

    function EmptyParam() {
      EmptyParam.__super__.constructor.call(this, "EmptyParam");
    }

    return EmptyParam;

  })(ObliqueNS.Param);

  ObliqueNS.EmptyParam = EmptyParam;

}).call(this);
