// Generated by CoffeeScript 1.7.1
(function() {
  var EmptyParam,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.ObliqueNS = this.ObliqueNS || {};

  EmptyParam = (function(_super) {
    __extends(EmptyParam, _super);

    function EmptyParam() {
      EmptyParam.__super__.constructor.call(this, "EmptyParam");
    }

    return EmptyParam;

  })(ObliqueNS.Param);

  ObliqueNS.EmptyParam = EmptyParam;

}).call(this);
