// Generated by CoffeeScript 1.10.0
(function() {
  var Directive;

  this.ObliqueNS = this.ObliqueNS || {};

  Directive = (function() {
    function Directive(name1, callback1, isGlobal) {
      this.name = name1;
      this.callback = callback1;
      this.isGlobal = isGlobal != null ? isGlobal : false;
      this._throwErrorIfParamsAreNotValid(this.name, this.callback);
    }

    Directive.prototype._isAFunction = function(memberToTest) {
      return typeof memberToTest === "function";
    };

    Directive.prototype._throwErrorIfParamsAreNotValid = function(name, callback) {
      if (!name || typeof name !== "string") {
        throw new ObliqueNS.Error("Directive name must be an string");
      }
      if (!this._isAFunction(callback)) {
        throw new ObliqueNS.Error("Directive must be called with a 'Constructor Function/Class' param");
      }
    };

    return Directive;

  })();

  ObliqueNS.Directive = Directive;

}).call(this);
