// Generated by CoffeeScript 1.7.1
(function() {
  var DirectiveProcessor;

  this.ObliqueNS = this.ObliqueNS || {};

  DirectiveProcessor = (function() {
    function DirectiveProcessor() {
      if (this === window) {
        return new DirectiveProcessor();
      }
      if (DirectiveProcessor._singletonInstance) {
        return DirectiveProcessor._singletonInstance;
      }
      DirectiveProcessor._singletonInstance = this;
      this._throwErrorIfJQueryIsntLoaded();
      this._directiveCollection = new ObliqueNS.DirectiveCollection();
      this._timedDOMObserver = this._createTimedDOMObserver(DirectiveProcessor.DEFAULT_INTERVAL_MS);
      jQuery(document).ready((function(_this) {
        return function() {
          _this._applyDirectivesInDOM();
          return _this._timedDOMObserver.observe();
        };
      })(this));
    }

    DirectiveProcessor.DEFAULT_INTERVAL_MS = 500;

    DirectiveProcessor.prototype._throwErrorIfJQueryIsntLoaded = function() {
      if (!window.jQuery) {
        throw new Error("DirectiveProcessor needs jQuery to work");
      }
    };

    DirectiveProcessor.prototype._createTimedDOMObserver = function(intervalInMs) {
      var observer;
      observer = new ObliqueNS.TimedDOMObserver(intervalInMs);
      observer.onChange((function(_this) {
        return function() {
          return _this._applyDirectivesInDOM();
        };
      })(this));
      return observer;
    };

    DirectiveProcessor._isApplyingDirectivesInDOM = false;

    DirectiveProcessor.prototype._applyDirectivesInDOM = function() {
      if (this._isApplyingDirectivesInDOM) {
        return;
      }
      this._isApplyingDirectivesInDOM = true;
      try {
        return $("*[data-directive]").each((function(_this) {
          return function(index, DOMElement) {
            var directive, directiveAttrValue, directiveName, model, obElement, _i, _len, _ref, _results;
            obElement = new ObliqueNS.Element(DOMElement);
            directiveAttrValue = obElement.getAttributeValue("data-directive");
            _ref = directiveAttrValue.split(",");
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              directiveName = _ref[_i];
              directiveName = directiveName.trim();
              if (obElement.hasFlag(directiveName)) {
                continue;
              }
              directive = _this._directiveCollection.getDirectiveByName(directiveName);
              if (!directive) {
                throw new ObliqueNS.Error("There is no " + directiveName + " directive registered");
              }
              obElement.setFlag(directiveName);
              model = _this._getModel(obElement);
              _results.push(new directive(DOMElement, model));
            }
            return _results;
          };
        })(this));

        /*
         *TODO: change this to a more human readable loop
        rootDOMElement = document.getElementsByTagName("body")[0]
        rootElement=new ObliqueNS.Element rootDOMElement
        
        rootElement.eachDescendant(
          (DOMElement) =>
            obElement=new ObliqueNS.Element(DOMElement)
            for cssExpr in @_directiveCollection.getCSSExpressions()
              continue if not obElement.matchCSSExpression cssExpr
              for directive in @_directiveCollection.getDirectivesByCSSExpression cssExpr
                directiveHashCode = directive.hashCode
                continue if obElement.hasFlag directiveHashCode
                obElement.setFlag directiveHashCode
                model=@_getModel obElement
                new directive DOMElement, model
        )
         */
      } finally {
        this._isApplyingDirectivesInDOM = false;
      }
    };

    DirectiveProcessor.prototype._getModel = function(obElement) {
      var dataModelExpr, model;
      model = Oblique().getModel();
      if (!model) {
        return void 0;
      }
      dataModelExpr = obElement.getAttributeValue("data-model");
      if (dataModelExpr === void 0) {
        return void 0;
      }
      if (dataModelExpr === "this") {
        return model;
      }
      try {
        return new ObliqueNS.JSON(model).getPathValue(dataModelExpr);
      } catch (_error) {
        return this._throwError("" + (obElement.getHtml()) + ": data-model doesn't match any data in model");
      }
    };

    DirectiveProcessor.prototype._throwError = function(errorMessage) {
      return Oblique().triggerOnError(new ObliqueNS.Error(errorMessage));
    };

    DirectiveProcessor.prototype.getIntervalTimeInMs = function() {
      return this._timedDOMObserver.getIntervalInMs();
    };

    DirectiveProcessor.prototype.setIntervalTimeInMs = function(newIntervalTimeInMs) {
      if (newIntervalTimeInMs <= 0) {
        throw new ObliqueNS.Error("IntervalTime must be a positive number");
      }
      this._timedDOMObserver.destroy();
      this._timedDOMObserver = this._createTimedDOMObserver(newIntervalTimeInMs);
      return this._timedDOMObserver.observe();
    };

    DirectiveProcessor.prototype.registerDirective = function(directiveConstructorFn) {
      return this._directiveCollection.add(directiveConstructorFn);
    };

    DirectiveProcessor.prototype.destroy = function() {
      var e;
      this._timedDOMObserver.destroy();
      try {
        return delete DirectiveProcessor._singletonInstance;
      } catch (_error) {
        e = _error;
        return DirectiveProcessor._singletonInstance = void 0;
      }
    };

    return DirectiveProcessor;

  })();

  ObliqueNS.DirectiveProcessor = DirectiveProcessor;

  this.Oblique = DirectiveProcessor;

}).call(this);
