// Generated by CoffeeScript 1.8.0
(function() {
  var Memory,
    __hasProp = {}.hasOwnProperty;

  this.ObliqueNS = this.ObliqueNS || {};

  Memory = (function() {
    function Memory() {
      this._vars = {};
    }

    Memory.prototype.setVar = function(name, value) {
      if (name === "Model") {
        throw new ObliqueNS.Error("Can't create a variable named 'Model', is a reserved word");
      }
      return this._vars[name] = value;
    };

    Memory.prototype.getVar = function(name) {
      return this._vars[name];
    };

    Memory.prototype.localVarsScript = function() {
      var script, variableName, variableValue, _ref;
      script = "";
      _ref = this._vars;
      for (variableName in _ref) {
        if (!__hasProp.call(_ref, variableName)) continue;
        variableValue = _ref[variableName];
        script = script + ("var " + variableName + "=this._memory.getVar(\"" + variableName + "\");");
      }
      return script;
    };

    return Memory;

  })();

  ObliqueNS.Memory = Memory;

}).call(this);
