// Generated by CoffeeScript 1.9.3
(function() {
  var Memory,
    hasProp = {}.hasOwnProperty;

  this.ObliqueNS = this.ObliqueNS || {};

  Memory = (function() {
    function Memory() {
      this._vars = {};
    }

    Memory.prototype.setVar = function(name, value) {
      if (name === "Model") {
        throw new ObliqueNS.Error("Can't create a variable named 'Model', is a reserved word");
      }
      return this._vars[name] = value;
    };

    Memory.prototype.getVar = function(name) {
      return this._vars[name];
    };

    Memory.prototype.localVarsScript = function() {
      var ref, script, variableName, variableValue;
      script = "";
      ref = this._vars;
      for (variableName in ref) {
        if (!hasProp.call(ref, variableName)) continue;
        variableValue = ref[variableName];
        script = script + ("var " + variableName + "=this._memory.getVar(\"" + variableName + "\");");
      }
      return script;
    };

    return Memory;

  })();

  ObliqueNS.Memory = Memory;

}).call(this);
