// Generated by CoffeeScript 1.7.1
(function() {
  var DirectiveProcessor;

  window.ObliqueNS = window.ObliqueNS || {};

  DirectiveProcessor = (function() {
    var Element;

    Element = ObliqueNS.Element;

    function DirectiveProcessor() {
      if (this === window) {
        return new DirectiveProcessor();
      }
      if (DirectiveProcessor._singletonInstance) {
        return DirectiveProcessor._singletonInstance;
      }
      DirectiveProcessor._singletonInstance = this;
      this._throwErrorIfJQueryIsntLoaded();
      this._intervalTimeInMs = DirectiveProcessor.DEFAULT_INTERVAL_MS;
      this._lastIntervalId = void 0;
      this._directiveCollection = new ObliqueNS.DirectiveCollection();
      this._listenToDirectivesInDOM();
    }

    DirectiveProcessor.DEFAULT_INTERVAL_MS = 500;

    DirectiveProcessor.prototype._throwErrorIfJQueryIsntLoaded = function() {
      if (!window.jQuery) {
        throw new Error("DirectiveProcessor needs jQuery to work");
      }
    };

    DirectiveProcessor.prototype._clearLastInterval = function() {
      if (this._lastIntervalId !== void 0) {
        return clearInterval(this._lastIntervalId);
      }
    };

    DirectiveProcessor.prototype._applyDirectivesOnDocumentReady = function() {
      return jQuery(document).ready((function(_this) {
        return function() {
          return _this._applyDirectivesInDOM();
        };
      })(this));
    };

    DirectiveProcessor.prototype._setNewInterval = function() {
      return this._lastIntervalId = setInterval((function(_this) {
        return function() {
          return _this._applyDirectivesInDOM();
        };
      })(this), this._intervalTimeInMs);
    };

    DirectiveProcessor.prototype._listenToDirectivesInDOM = function() {
      this._clearLastInterval();
      this._applyDirectivesOnDocumentReady();
      return this._setNewInterval();
    };

    DirectiveProcessor._isApplyingDirectivesInDOM = false;

    DirectiveProcessor.prototype._applyDirectivesInDOM = function() {
      var rootElement, rootObElement;
      if (this._isApplyingDirectivesInDOM) {
        return;
      }
      this._isApplyingDirectivesInDOM = true;
      try {
        rootElement = document.getElementsByTagName("body")[0];
        rootObElement = new ObliqueNS.Element(rootElement);
        return rootObElement.eachDescendant((function(_this) {
          return function(DOMElement) {
            var cssExpr, directive, directiveName, obElement, _i, _len, _ref, _results;
            obElement = new ObliqueNS.Element(DOMElement);
            _ref = _this._directiveCollection.getCSSExpressions();
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              cssExpr = _ref[_i];
              if (!obElement.matchCSSExpression(cssExpr)) {
                continue;
              }
              _results.push((function() {
                var _j, _len1, _ref1, _results1;
                _ref1 = this._directiveCollection.getDirectivesByCSSExpression(cssExpr);
                _results1 = [];
                for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                  directive = _ref1[_j];
                  directiveName = directive.name;
                  if (obElement.hasFlag(directiveName)) {
                    continue;
                  }
                  obElement.setFlag(directiveName);
                  _results1.push(new directive(DOMElement));
                }
                return _results1;
              }).call(_this));
            }
            return _results;
          };
        })(this));
      } finally {
        this._isApplyingDirectivesInDOM = false;
      }
    };

    DirectiveProcessor.prototype.getIntervalTimeInMs = function() {
      return this._intervalTimeInMs;
    };

    DirectiveProcessor.prototype.setIntervalTimeInMs = function(newIntervalTimeInMs) {
      if (newIntervalTimeInMs <= 0) {
        throw new ObliqueNS.Error("IntervalTime must be a positive number");
      }
      this._intervalTimeInMs = newIntervalTimeInMs;
      return this._listenToDirectivesInDOM();
    };

    DirectiveProcessor.prototype.registerDirective = function(directiveConstructorFn) {
      return this._directiveCollection.add(directiveConstructorFn);
    };

    DirectiveProcessor.prototype.destroy = function() {
      var e;
      this._clearLastInterval();
      try {
        return delete DirectiveProcessor._singletonInstance;
      } catch (_error) {
        e = _error;
        return DirectiveProcessor._singletonInstance = void 0;
      }
    };

    return DirectiveProcessor;

  })();

  ObliqueNS.DirectiveProcessor = DirectiveProcessor;

  window.Oblique = DirectiveProcessor;

}).call(this);
