// Generated by CoffeeScript 1.7.1
(function() {
  var TimedDOMObserver;

  this.ObliqueNS = this.ObliqueNS || {};

  TimedDOMObserver = (function() {
    function TimedDOMObserver() {
      this._reset();
      this._callback = void 0;
      this._intervalInMs = 500;
    }

    TimedDOMObserver.prototype.onChange = function(callback) {
      return this._callback = callback;
    };

    TimedDOMObserver.prototype.setIntervalInMs = function(newIntervalInMs) {
      return this._intervalInMs = newIntervalInMs;
    };

    TimedDOMObserver.prototype.observe = function() {
      this.destroy();
      if (!this._callback) {
        return;
      }
      return this._intervalId = setInterval((function(_this) {
        return function() {
          return _this._callback();
        };
      })(this), this._intervalInMs);
    };

    TimedDOMObserver.prototype._reset = function() {
      return this._intervalId = void 0;
    };

    TimedDOMObserver.prototype.destroy = function() {
      if (this._intervalId) {
        clearInterval(this._intervalId);
        return this._reset();
      }
    };

    return TimedDOMObserver;

  })();

  ObliqueNS.TimedDOMObserver = TimedDOMObserver;

}).call(this);
